version: "3.8"

services:
  mysql:
    container_name: "mysql-new"
    image: "mysql"
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: "devops"
    volumes:
      - "mysql_data:/var/lib/mysql"
    networks:
      - "two_tier"
    restart: "always"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-proot"]
      interval: 10s
      timeout: 5s
      retries: 5

  flask:
    container_name: "two_tier-flask"
    build:
      context: .
    ports:
      - "5000:5000"
    environment:
      MYSQL_HOST: "mysql"
      MYSQL_USER: "root"
      MYSQL_PASSWORD: "root"
      MYSQL_DB: "devops"
    networks:
      - "two_tier"
    restart: "always"
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:5000/"]  
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s
    depends_on:
      mysql:
        condition: "service_healthy"

volumes:
  mysql_data:
networks:
  two_tier:

